# Generated by Django 4.1 on 2022-09-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_lead_is_sent_lead_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='ad_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='adset_name',
            field=models.CharField(default='MAIN', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='campaign_name',
            field=models.CharField(default='main', max_length=255),
            preserve_default=False,
        ),
    ]
