# Generated by Django 4.1 on 2022-09-12 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_lead_ad_name_lead_adset_name_lead_campaign_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='form_id',
        ),
    ]
